module:
  imports:
  - path: github.com/hugo-mods/icons
  replacements:
  - github.com/hugo-mods/icons -> ../../.

Params:
  # These parameters are optional, they reflect the internal defaults:
  mod_icons:
    enableAutoTitle: true
    enableStats: true
    defaultLoader: svg-use
    defaultLoaderShortcode: svg-inline
    iconBaseClass: icon
